#!/bin/bash

NUM1=100
NUM2=200
NAME="BHAGHAWAN RAMANA"

SUM=$(($NUM1+$NUM2))

echo "Total sum value is : ${SUM}"

LEADERS=("modi" "putin" "trump")
echo" All leaders :: ${LEADERS}"
echo " All leaders :: ${LEADERS[@]}"
echo "first leader :: ${LEADERS[0]}"